export const SEARCH_INPUT_FOCUS = 'header/search_input_focus'
export const SEARCH_INPUT_BLUR = 'header/search_input_blur'
export const GET_TIPS = 'header/GET_TIPS'
export const TIP_ENTER = 'header/TIP_ENTER'
export const TIP_LEAVE = 'header/TIP_LEAVE'
export const NEXT_PAGE = 'header/NEXT_PAGE'